### ISSUE TITLE
Pregunta: ¿Existe soporte para los tipos en Cypress + Typescript?

### ISSUE THREAD

**Issue by JoanEsquivel** [sclavijosuero/cypress-ajv-schema-validator#3]
Hola, 

Estaba intentando integrar el plugin en un proyecto de Cypress con Typescript y noté el siguiente error:

![image](https://github.com/user-attachments/assets/08097136-4973-4464-9ca7-005a7e3644f4)

![image](https://github.com/user-attachments/assets/680c82ae-d000-43ac-9dc7-05248f632f4d)

Probablemente sea capa 8, pero he notado que otros plugins necesitan tipos personalizados y se referencian en el tsconfig.json como por ejemplo: 

![image](https://github.com/user-attachments/assets/794ee4e4-6ab9-45a3-8a41-3cbad658d874)

¿De casualidad sabes si este error esta relacionado a lo antes mencionado?

Gracias de antemano.

**Comment by sclavijosuero** [comment]
Perfect! Thank you Joan for letting me know.
